dist: trusty
sudo: required
  - env: COMPILER=clang++-7 BUILD_TYPE=Debug GSL_CXX_STANDARD=17
      addons: &clang70
        apt:
          packages:
            - clang-7
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

before_script:
  - sudo apt-get install libboost-test-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo -E add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo -E apt-get update
  - sudo apt-get install cmake
#  - sudo apt-get install libgtest-dev -y
#  - sudo apt-get --allow-unauthenticated -y upgrade cmake # install cmake
#  - cd /usr/src/gtest
#  - sudo env "PATH=$PATH" cmake CMakeLists.txt
#  - sudo make
#  - sudo cp *.a /usr/lib
#  - sudo mkdir /usr/local/lib/gtest
#  - sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
#  - sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo  ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo  ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - gcc -v && g++ -v && cmake --version
  - sudo cmake .
  - sudo cmake --build .
#  - sudo cmake --build . --target test
  - sudo cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    -sudo curl -T otus_2-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u stirlitzi:$BINTRAY_API_KEY "https://api.bintray.com/content/test194/otus2_ipfilter/otus_2/$TRAVIS_BUILD_NUMBER/otus_2-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

